### ISSUE TITLE
Missing parentheses when print "x | (y & z)"

### ISSUE THREAD

**Issue by Ric0rdanza** [RobinWebbers/vfs-1b-dpll#1]
Output like:
```
ghci> parse "x | (y & z)"
"x" ∨ "y" ∧ "z"
ghci> parse "x & (y | z)"
"x" ∧ ("y" ∨ "z")
ghci> parse "(x & y) | z"
"x" ∧ "y" ∨ "z"
ghci> parse "(x | y) & z"
("x" ∨ "y") ∧ "z"
```
The first line was supposed to be `"x" ∨ ("y" ∧ "z")`, but the parentheses were missing.

**Comment by RobinWebbers** [comment]
Hi there,

We've defined the precedence of conjunction (`inflixl 7 :&:`) to be larger than that of disjunction ('infixl 6 :|:'). As such, the parentheses are correct, as `x | (y & z)` and `x | y & z` are parsed equivalently!

This is also the reason why the parentheses for the 3rd example are dropped (the meaning doesn't change).
But the 4th example doesn't drop the parenthesis as this **would** change the meaning!

Cheers,
Robin
